hedge_comm_demo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: HedgeCommDemoBundle:Default:index }

hedge_comm_demo_test:
  pattern: /haha
  defaults: { _controller: HedgeCommDemoBundle:Default:haha }