parameters:
#    hedge_comm_demo.example.class: HedgeComm\DemoBundle\Example

services:
#    hedge_comm_demo.example:
#        class: %hedge_comm_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
